#!/bin/bash

# Set the python environment
source venv/bin/activate

# Set the directory paths
cpath=`pwd`
echo "cpath set to: -- ${cpath%} --"
export ANSIBLE="${cpath%/tests/integration/harness}"
#export ANSIBLE="${cpath%/../../..}"
echo "ANSIBLE set to: -- ${ANSIBLE} --"

#export ANSIBLE_CONFIG=/home/bjorn/ansible/ansible_collections.extreme.fe/ansible_collections/extreme/fe/tests/integration/harness/cfg/ansible.cfg
export ANSIBLE_CONFIG="${cpath}/cfg/ansible.cfg"
echo "ANSIBLE_CONFIG set to: -- ${ANSIBLE_CONFIG} --"

#export ANSIBLE=/home/rwa/work/ansible_collections.extreme.fe/ansible_collections/extreme/fe && echo "ANSIBLE set to: $ANSIBLE"

# Source the GNS3 configuration
source cfg/gns3.cfg

# ------------------------------------------------------------------------------
# Stop the servers ...
# ------------------------------------------------------------------------------

# Check if the dashboard server is running, if so stop it
P=`ps -ef |grep dashboard_server.py | grep -v "grep" | grep python3 | awk '{ print $2 }'`
if [ -n "$P" ]; then
  echo "Stopping dashboard server..."
  kill -9 $P
else
  echo "Dashboard server is not running."
fi  

# See if the gns3server is running, if so stop it
P=`ps -ef |grep gns3server | grep -v "grep" | grep python3 | awk '{ print $2 }'`
if [ -n "$P" ]; then
  # See if there the project exisis, if so, close it first
  echo "Removing GNS3 project..."
  remove_gns3_project
  echo "Stopping GNS3 server..."
  kill -9 $P
else
  echo "GNS3 server is not running." 
fi

