name: Ansible Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    name: Sanity ({{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          - stable-2.14
          - stable-2.15
          - devel
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/extreme/fe

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ansible-base
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: ansible_collections/extreme/fe
