#!/bin/bash

ORIG=$1
DEST=$2

if ! [ -f DT.9.1.0.0int049-bjorn${ORIG}-free.qcow2 ] ; then
	echo "Could not file: DT.9.1.0.0int049-bjorn${ORIG}-free.qcow2"
	exit 1
fi

if [ "${DEST}" = "" ] ; then
	echo "You must specify a second argument"
	exit 1
fi

# Copy the file
cp DT.9.1.0.0int049-bjorn${ORIG}-free.qcow2 DT.9.1.0.0int049-bjorn${DEST}-free.qcow2

# create the link
ln -s DT.9.1.0.0int049-bjorn${DEST}-free.qcow2 voss-${DEST}.qcow2

# Mount the image
./mount_images voss-${DEST}.qcow2

# change the Serial#
cat /mnt/dt1/flash/net.conf | sed "s/voss-dt-${ORIG}/voss-dt-${DEST}/" >/tmp/clone.net.conf
cp /tmp/clone.net.conf /mnt/dt1/flash/net.conf

# Unmount the image
./mount_images

# Create the md5sum
md5sum voss-${DEST}.qcow2 | awk '{ print $1 }' > voss-${DEST}.qcow2.md5sum

echo "cloned DT.9.1.0.0int049-bjorni${ORIG}-free.qcow2 to DT.9.1.0.0int049-bjorn${DEST}-free.qcow2"



