#!/bin/bash

Device=$1
Type=$2

set -e

XIQEMU_HOST="192.168.1.121"
TEMP_NETCONF_FILE=/tmp/net_conf.txt

if [ "$Device" = "" ] ; then
	echo "ERROR: Must enter Device# as first argument"
	exit 1
fi

if [ "$Type" = "" ] ; then
	# Reuse the type that already exist
	if ! [ -f voss-${Device}.cfg ] ; then
		echo "ERROR: Must enter Device Type as second argument"
		exit 1
	fi
	Type=`ls -la voss-${Device}.cfg | awk '{ print $11 }' | sed 's/\./ /g' | awk '{ print $1 '}`
fi

if ! [ -f ${Type}.cfg ] ; then
	echo "ERROR: Default configuration file: ${Type}.cfg does not exist"
	exit 1
fi

# Create a link to the config, so we can use this when we wnat to update
ln -sf ${Type}.cfg voss-${Device}.cfg

# First create a copy of the base distribution file
BASE_V=`ls -la base.qcow2 | awk '{ print $11 }'`
cp base.qcow2 voss-${Device}.${BASE_V}

# Create the link
ln -sf voss-${Device}.${BASE_V} voss-${Device}.qcow2 

PLAT=${Type}

if [ ${Type} = "5420F-16W-32P-4XE" ] ; then
	PLAT="X445F-16W-32P-4XE"
fi
if [ ${Type} = "7520-48XT-6C" ] ; then
	PLAT="7520-48XT"
fi
if [ ${Type} = "5520-48T" ] ; then
	PLAT="X455-48T"
fi
if [ ${Type} = "5520-48SE" ] ; then
	PLAT="X455-48SE"
fi
if [ ${Type} = "5520-24T" ] ; then
	PLAT="X455-24T"
fi

echo "Creating voss-dt-${Device} ${Type} (DT MAP:${PLAT}) from ${BASE_V}"

# Create the net.conf file
echo "{" >${TEMP_NETCONF_FILE}
echo "	\"platform\": \"${PLAT}\"," >>${TEMP_NETCONF_FILE}
echo "	\"serial_number\":\"voss-dt-${Device}\"," >>${TEMP_NETCONF_FILE}
echo "	\"cloud-server\":\"${XIQEMU_HOST}\"," >>${TEMP_NETCONF_FILE}
echo "	\"cloud-server-type\":\"aio\"," >>${TEMP_NETCONF_FILE}
echo "}" >>${TEMP_NETCONF_FILE}

./mount_images || true

# mount the qcow2 image
./mount_images voss-${Device}.qcow2

# copy the net.conf file
cp ${TEMP_NETCONF_FILE} /mnt/dt1/flash/net.conf

# Copy the appfs file
cp appfs.tgz /mnt/dt1/a/appfs.tgz

# Copy the default-test config file
cp ${Type}.cfg /mnt/dt1/flash/start_test.cfg

# unmount the image
./mount_images

# Create the md5sum
md5sum voss-${Device}.qcow2 | awk '{ print $1 }' > voss-${Device}.qcow2.md5sum
