#!/bin/bash

#
# Script that edits the net.conf inside an image
#

IMAGE=$1

if [ "$IMAGE" = "" ] ; then
	echo "Specify an image file as the first argument"
	exit 1
fi

if ! [ -f $IMAGE ] ; then
	echo "Image file $IMAGE not found"
	exit 1
fi

# unmount any images
./mount_images

# Mount the image
./mount_images $IMAGE

# edit the file
if ! [ -f /mnt/dt1/flash/net.conf ] ; then
	echo "net.conf file not found"
else
	vim /mnt/dt1/flash/net.conf
fi

# unmount the image
./mount_images

# re-create the md5sum
echo "Creating md5sum of image: $IMAGE"
md5sum $IMAGE | awk '{ print $1 }' > $IMAGE.md5sum
