#!/bin/bash

set -e

IMAGE=$1

if [ "$IMAGE" = "" ] ; then

  # See if we have mounted stuff
  M=`mount | grep " /mnt/dt" | awk '{ print $3 }'`
  if [ "$M" = "" ] ; then
    echo "No Image mounted"
  else
    sleep 2
    umount /mnt/dt1
    #umount /mnt/dt2
    #umount /mnt/dt3
    sleep 1
    qemu-nbd --disconnect /dev/nbd0
    #rmmod nbd
    echo "Image unmounted"
  fi
  exit 0
fi

if ! [ -f $IMAGE ] ; then
  echo "Can't find file: $IMAGE"
  exit 1
fi

modprobe nbd max_part=8
qemu-nbd --connect=/dev/nbd0 $IMAGE

fdisk /dev/nbd0 -l

mount /dev/nbd0p1 /mnt/dt1
#mount /dev/nbd0p2 /mnt/dt2
#mount /dev/nbd0p3 /mnt/dt3

echo "File systems from imeg $IMAGE mounted on /mnt/dt1 through /mnt/dt3"

