---
- name: Gather Fabric Engine configuration facts
  hosts: gns3_network
  gather_facts: false
  tasks:
    - name: Collect config subset
      extreme.fe.extreme_fe_facts:
        gather_subset:
          - config
      register: fe_config

    - name: Show configuration facts
      debug:
        var: fe_config.ansible_facts.extreme_fe_facts.config
