---
- name: Remove port 1:6 from VLAN 5 on ExtremeNetworks Fabric Engine switches
  hosts: gns3_network
  gather_facts: false
  tasks:
    - name: Ensure VLAN 5 exists
      extreme.fe.extreme_fe_vlans:
        vlan_id: 5
        vr_name: GlobalRouter
        state: merged

    - name: Remove VLAN 5 from interface 1:6
      extreme.fe.extreme_fe_l2_interfaces:
        interface: PORT:1:6
        remove_tagged_vlans: [5]
        untagged_vlan: 5
        state: deleted
