#!/bin/bash

#
# Script that updates the appfs inside an image
#

set -e

# Check if we have an argument
if ! [ "$1" = "" ] ; then
	# See if this file exists
	if ! [ -f "$1" ] ; then
		echo "Error release $1 not found"
		exit 1
	fi
	echo "Updating all DT's to distribution: $1"
	rm -rf base.qcow2 base.qcow2.md5
	ln -s $1 base.qcow2
fi

# make sure we're sudo
P=`id | grep root | wc -l`
if [ "$P" = "0" ] ; then
	echo "Error: You must run this script as sudo"
	exit 1
fi


List=`ls -1 voss-?.cfg voss-??.cfg | sed 's/-/ /g' | sed 's/\./ /g' | awk '{ print $2 }'`
if [ "$List" = "" ] ; then
	echo "ERROR: Not DT images found to update"
	exit 1
fi

for i in $List
do
	echo "Updating $i"
	./createDT $i 
done
