#!/bin/bash

#
# Script that updates the appfs inside an image
#

set -e

IMAGE=$1
APPFS=$2

if ! [ "$IMAGE" = "all" ] ; then

	if [ "$IMAGE" = "" ] ; then
		echo "Specify an image file as the first argument"
		exit 1
	fi

	if ! [ -f $IMAGE ] ; then
		echo "Image file $IMAGE not found"
		exit 1
	fi
else
  IMAGE=" \
  	voss-1.qcow2 \
  	voss-2.qcow2 \
  	voss-3.qcow2 \
  	voss-4.qcow2 \
  	voss-5.qcow2 \
  	voss-6.qcow2 \
  	voss-7.qcow2 \
  	voss-8.qcow2 \
  	voss-9.qcow2 \
  	voss-10.qcow2 \
  	voss-11.qcow2 \
  	voss-12.qcow2 \
  	voss-13.qcow2 \
  	voss-14.qcow2 \
  	voss-15.qcow2 \
  	voss-16.qcow2 \
	"
fi

if [ "$APPFS" = "" ] ; then
	echo "Specify an appfs file as the second argument"
	exit 1
fi

if ! [ -f $APPFS ] ; then
	echo "APPFS file $APPFS not found"
	exit 1
fi

for i in $IMAGE
do
	if [ -f "$i" ] ; then

		echo "*** Updating image $i ***"

		# unmount any images
		./mount_images || true

		# Mount the image
		./mount_images $i

		cp $APPFS /mnt/dt1/a/appfs.tgz

		# unmount the image
		./mount_images

		# re-create the md5sum
		echo "Creating md5sum of image: $i"
		md5sum ${i} | awk '{ print $1 }' > ${i}.md5sum

		sleep 2
	else
		echo " *** $i not found, skipping ***"
	fi
done
