galaxy_info:
  author: Extreme Networks
  description: Configure VLANs on Extreme Fabric Engine
  company: Extreme Networks
  license: GPL-3.0-or-later
  min_ansible_version: 2.9
  platforms:
  - name: Extreme Fabric Engine
    versions:
    - all
  categories:
  - networking
dependencies: []
