namespace: extreme
name: fe
version: 1.0.0
readme: README.md
authors:
  - Extreme Networks
description: Ansible Collection for Extreme Networks Fabric Engine
license:
  - GPL-3.0-or-later
build_ignore:
  - tests/integration
  - tests/output
  - .github
  - scripts
  - playbooks
  - venv
  - .gitignore
  - .gitattributes
  - .vscode
  - .idea
  - dist
  - roles/vlans
  - "*.tar.gz"
tags:
  - networking
  - extreme
  - fabric engine
repository: https://github.com/extremenetworks/ansible_collections.extreme.fe
documentation: https://github.com/extremenetworks/ansible_collections.extreme.fe
homepage: https://github.com/extremenetworks/ansible_collections.extreme.fe
issues: https://github.com/extremenetworks/ansible_collections.extreme.fe/issues
