#!/bin/bash

# Global UUID:
UUID_PROJ=""
UUID_UNET=""
UUID_MGMT_SW=""
UUID_SROUTER=""
TEMPLATE_TPC=""

# 1 Main Mgt switch + 6 extra Mgmt switches
for i in {0..6}
do
    UUID_SW[$i]=""
done

# 16 VOSS Devices
for i in {1..16}
do
    UUID_VOSS_DT[$i]=""
done

# 2 Traffic PC's
for i in {1..2}
do
    UUID_TPC[$i]=""
done

# net.conf supported platforms:
# 
# 5320: 5320-<XXX>
#            <XXX> one of 48T-8XE 48P-8XE 24T-8XE 24P-8XE 16P-4XE 16P-4XE-DC 16P-2XT-2X
#
# 5420: X445F-<XXX>
#             <XXX> one of 24P-4XE 8W-16P-4XE 24T-4XE 48P-4XE 16W-32P-4XE 48T-4XE 24S-4XE 48P-4XL 16MW-32P-4XE
#       X445M-<XXX>
#             <XXX> one of 24T-4YE 24W-4YE 48T-4YE 48W-4YE 16MW-32P-4YE 
#       4220-<XXX>
#            <XXX> one of: 12T-4X 12P-4X 24T-4X (24T-4X-XT) 24P-4X 48T-4X 48P-4X 8X (24T-24S-4XE-XT) 4MW-8P-4X
#                          4MW-20P-4X 8MW-40P-4X  
#            >>> 5420F-16W-32P-4XE = x445F-16W-32P-4XE = +oob = 16x POE 90W & 32x POE+ & 4x 10G SFP+ & 2x SFP-DD & 1 oob -> total of 52+1 = 53 ports
# 
# 5520: X455-<XXX>
#            <XXX> one of: 48T 48W 12-MW-36W 24T 24W 24X 48SE 24T-ACDC 48T-ACDC 24X-ACDC 48SE-ACDC 
#
# 5720: 5720-<XXX>
#            <XXX> one of: 24MW 48MW 24MXW 48MXW 
#
# 7520: 7520-<XXX>
#            <XXX> one of: 48Y 48XT 48YE-8CE 48XT-6C
#            >>> 7520-48XT-6C = 7520-48XT = 48 1/10GB & 6 40/100 QSFP + oob = 54 + 1 = 55 ports
#
# 7720: 7720-<XXX>
#            <XXX> one of 32C 
#            >>> 7720-32C = 7720-32C = 32x 40G/100G & oob = 32 + 1 = 33 ports, 
#
# 7830: 7830-<XXX>
#            <XXX> one of: 32CE-8DE 
#
# 8730: 8730-<XXX>
#            <XXX> oone of: 32D
#
# 7400: T3X048V (7400-48Y-8C)
#
# 4900: VSP4900-<XXX>
#               <XXX> one of: 24P 48P 24XE 12MXU-12XE 24S
#
# 

# DT 1:  5420F-16W-32P-4XE (53)
# DT 2:  5420F-16W-32P-4XE (53) -> 5320-16P-4XE (20 ?)
# DT 3:  7520-48XT-6C (55)
# DT 4:  5520-48W (49 ?)        -> 5520-48T   (49)
# DT 5:  5520-12-MW-36W (49)    -> 5520-48SE  (49)
# DT 6:  5520-24X (25)          -> 5520-24T   (25)
# DT 7:  5720-48Y (49 ?)        -> 5720-48MW (49)
# DT 8:  5720-48YE-8CE (57 ?)   -> 5720-24MXW (25)
# DT 9:  7520-48YE-8CE (57 ?)
# DT 10: 7720-32C (33)
# DT 11: 7830-32CE-8DE (41 ?)   -> chrashes on boot in vlan add
# DT 12: 8730-32D (33 ?)
# DT 13: 7400-48Y-8C (57 ?)
# DT 14: 4900-48P (49 ?)
# DT 15: 5320-48P-8XE (56 ?)
# DT 16: 5320-24T-8XE (32 ?)


echoErrRed() { printf "\e[31;1m%s\e[0m\n" "$*" >&2; }
echoErrGreen() { printf "\e[92;1m%s\e[0m\n" "$*" >&2; }

test_func () {
    echoErrGreen "Error: Green"
    return 
}

#
# Function to issue a start to the gns3 for a given node
#
start_node () {
    if [ "$UUID_PROJ}" = "" ] ; then
        echo "ERROR: No project UUID found, cannot start node"
        return 1;
    fi
    NODE_ID=$1
    curl --fail --silent --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${NODE_ID}/start" --data "{}" > /dev/null
    return 0
}

#
# Function that starts all nodes in a project
#
start_all_nodes () {
    if [ "$UUID_PROJ}" = "" ] ; then
        echo "ERROR: No project UUID found, cannot start node"
        return 1;
    fi

    # Get all the nodes
    RESULT=$(curl --fail --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes" | jq -r '.[].node_id') 
    if [ -n "$GNS3_DEBUG" ]; then
        echo "RESULT:$RESULT"
    fi

    # Re-iterate through all nodes and if they have not been started, start them
    for NODE_ID in $RESULT; do
        # Get the status of the node
        NODE_STATUS=$(curl  --fail --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${NODE_ID}" | jq -r '.status')
        #echo "NODE_ID:$NODE_ID STATUS:$NODE_STATUS"
        if [ "$NODE_STATUS" != "started" ] ; then
            echo "Starting node UUID:$NODE_ID (status:$NODE_STATUS)"
            start_node $NODE_ID
        fi
    done
}

#############################################################
## Connect 2 nodes together
#############################################################
connect_nodes () {
    NODE_ID_1=$1
    AD_1=$2
    PORT_1=$3
    TEXT1=$4
    NODE_ID_2=$5
    AD_2=$6
    PORT_2=$7
    TEXT2=$8

    curl --fail --silent --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/links" --data "{\
        \"nodes\": [\
            {\"node_id\": \"${NODE_ID_1}\", \"adapter_number\": ${AD_1}, \"port_number\": ${PORT_1}, \"label\": {\"text\": \"${TEXT1}\"}}, \
            {\"node_id\": \"${NODE_ID_2}\", \"adapter_number\": ${AD_2}, \"port_number\": ${PORT_2}, \"label\": {\"text\": \"${TEXT2}\"}}\
            ]}" >/dev/null
}

#############################################################
## Start a DT
## ARGS: <NAME> <DEVICE_OS> <DEVICE#> <DEVICE_MAC> <NUM_PORTS> <DISK_IMG> <XPOS> <YPOS> <SW_NR> <SW_PORT> 
##
#############################################################
create_dt () {

    NAME=$1
    DEVICE_OS=$2
    DEVICE_NUM=$3
    DEVICE_MAC=$4
    NUM_PORTS=$5
    DISK_IMG=$6
    XPOS=$7
    YPOS=$8
    SW_NR=$9
    SW_PORT=${10}

    COMPUTE_ID="local"

    NODE_NAME="${DEVICE_OS}-dt${DEVICE_NUM}-${NAME}"

    # 5320 does not have an oob port!
    DEV_FAM=`echo ${NAME} | sed 's/-/ /g' | awk '{ print $1 }'`

    FIRST_PORT_NAME="Mgmt"
    ADAPTER="0"
    MGMT_PORT="Mgmt"
    if [ "${DEV_FAM}" = "5320" ] ; then
        FIRST_PORT_NAME="N/A"   
        ADAPTER="1"
        MGMT_PORT="1/1"
    fi

    # Determine with switch port to connect the oob port to
    if [ "${DEVICE_OS}" = "voss" ] ; then
      # VOSS devices connect to Switch ports 3,4,5,6,7
      OS_NUM=2
    else 
      # EXOS devices connect to port 1 and 2
      OS_NUM=0 
    fi
    
    echo "Creating ${NODE_NAME}: Image:$DISK_IMG MAC:$DEVICE_MAC"
    # TYPE:5420F-16W-32P-4XE"

    # Get the project UUID
    UUID_PROJ=$(get_project_UUID)
    
    # Create a new instance
    
    RESULT=$(curl --fail --silent --show-error --location --request POST \
      "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes" \
      --data "{ \
        \"name\": \"${NODE_NAME}\", \
        \"compute_id\": \"${COMPUTE_ID}\", \
        \"x\": ${XPOS}, \
        \"y\": ${YPOS}, \
        \"node_type\": \"qemu\", \
        \"symbol\": \":/symbols/affinity/circle/gray/switch_multilayer.svg\", \
        \"first_port_name\": \"${FIRST_PORT_NAME}\", \
        \"port_name_format\": \"1/{port1}\", \
        \"properties\": { \
            \"platform\": \"x86_64\", \
            \"hda_disk_image\": \"${DISK_IMG}\", \
            \"ram\": 2048, \
            \"cpus\": 2, \
            \"on_close\": \"power_off\", \
            \"adapters\": ${NUM_PORTS}, \
            \"mac_address\": \"${DEVICE_MAC}\", \
            \"boot_priority\": \"c\", \
            \"process_priority\": \"normal\", \
            \"adapter_type\": \"e1000\", \
            \"hda_disk_interface\": \"ide\", \
            \"options\": \"-enable-kvm\" \
      } \
    }")

    UUID_NODE=$(jq --raw-output ".node_id" <<< "${RESULT}")

    # Need to ADD check for EXOS -- ** --
    UUID_VOSS_DT[$DEVICE_NUM]=${UUID_NODE}
    echo "  Created DT: ${NODE_NAME} UUID:${UUID_NODE}"

    # Connect the DT to the mgmt network
    connect_nodes "${UUID_NODE}" "$ADAPTER" "0" "$MGMT_PORT" "${UUID_SW[$SW_NR]}" "0" "${SW_PORT}" "${SW_PORT}"

}

#############################################################
# Function to create a Traffic PC
#############################################################
# Create the Traffic PC node: 
# create_tpc "TPC-1" $pct_id 1   45 -330 "02:42:d0:aa:00:50" &
#
create_tpc () {

    NAME=$1
    TPL=$2
    PC_NR=$3
    XPOS=$4
    YPOS=$5
    MAC=$6

    # See if we have a TPC template
    if [ "$TEMPLATE_TPC" == "" ] ; then
       # We may need to create a new template for the TPC
       echo "Check if traffic template exists"
       
        R=`curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates" | grep "TrafficPC" | wc -l`
        if [ "$R" = "0" ] ; then

            # Template is not available, create it
            echo "  TrafficPC template not installed, adding new TrafficPC template"
            R=`curl --fail --silent --show-error --location -X POST http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates \
                -H "Content-Type: application/json" \
                -d '{ \
                "name": "TrafficPC", \
                "template_type": "docker", \
                "compute_id": "local", \
                "image": "pc:latest", \
                "adapters": 6, \
                "console_type": "telnet" \
                }'`
        fi
	echo "Retrieve the traffic template"

        # Retrieve the Traffic PC templace ID
        TEMPLATE_TPC=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates" | jq -r '.[] | select(.name=="TrafficPC") | .template_id')
    fi
    echo "  Using TrafficPC template ID: $TEMPLATE_TPC"

    # Create the TPC now
    RESULT=$(curl --fail --silent --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/templates/$TEMPLATE_TPC" --data "{\"name\": \"$NAME\", \"compute_id\": \"${COMPUTE_ID}\", \"x\": $XPOS, \"y\": $YPOS}")
    UUID_TPC_L=$(jq --raw-output ".node_id" <<< "${RESULT}")
    echo "  TrafficPC $NAME: UUID:$UUID_TPC_L"
    curl --fail --silent --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_TPC_L}" --data "{\"name\": \"$NAME\"}" > /dev/null
    curl --fail --silent --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_TPC_L}" --data "{\"symbol\": \":/symbols/affinity/circle/gray/laptop.svg\"}" > /dev/null
    curl --fail --silent --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_TPC_L}" --data "{\"properties\": {\"adapters\": 6, \"mac_address\": \"$MAC\" }}" > /dev/null

    UUID_TPC[${PC_NR}]="${UUID_TPC_L}"
}

#############################################################
# Function to create a switch
#   Mgtmt Switch = 0, L2_SW = 1 ... n
#############################################################
create_switch () {
    NAME=$1
    SW_NR=$2
    XPOS=$3
    YPOS=$4
    LABEL_XPOS=$5
    LABEL_YPOS=$6

    echo "Create switch: $NAME (switch:$SW_NR)"
    COMPUTE_ID="local"

    # See if the switch is already there, if it is delete it
    # RESULT=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_BE_HOST}:${GNS3_BE_PORT}/v2/projects/${UUID_PROJ}/nodes")
    # UUID_NODE=$(jq --raw-output ".[] | select( .name == \"$NAME\" ).node_id" <<< "${RESULT}")
    # test -n "${UUID_NODE}" && curl --fail --silent --show-error --location --request DELETE "http://${GNS3_BE_HOST}:${GNS3_BE_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_NODE}" > /dev/null || true

    # Now create a new one
    RESULT=$(curl --fail --silent --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/templates/1966b864-93e7-32d5-965f-001384eec461" --data "{\"name\": \"${NAME}\", \"compute_id\": \"${COMPUTE_ID}\", \"x\": $XPOS, \"y\": $YPOS}")
    
    UUID_NODE=$(jq --raw-output ".node_id" <<< "${RESULT}")
    curl --fail --silent --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_NODE}" \
        --data "{\"name\": \"${NAME}\"}" > /dev/null
    curl --fail --silent --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_NODE}" \
        --data "{\"symbol\": \":/symbols/affinity/square/gray/interconnect.svg\",\
        \"label\": {\"rotation\": 0, \"style\": \"null\", \"text\": \"LAN\", \"x\": $LABEL_XPOS, \"y\": $LABEL_YPOS}}" > /dev/null

    echo "Created switch: $NAME (switch:$SW_NR) UUID:${UUID_NODE}"

    # Save the Mgmt_SW_NODE ID for later use
    UUID_SW[${SW_NR}]="${UUID_NODE}"

    if [ "${SW_NR}" = "0" ] ; then
        # Save the MGMT_SW_NODE ID for later use
        UUID_MGMT_SW="${UUID_NODE}"

        # Link the Mgmt_SW to the SubNetRouter
        connect_nodes ${UUID_SROUTER} 1 0 "1" ${UUID_NODE} 0 0 "0"
    else
        # Link this extra Mgmt switch to the central Mgmt switch node ...
        #UUID_MGMT_SW=$(get_switch_UUID "Mgmt_SW")
        connect_nodes ${UUID_NODE} 0 0 "0" ${UUID_SW[0]} 0 ${SW_NR} ${SW_NR}
    fi
}

#
# Execute a rest API on a DT
#
exec_rest() {
    
    Device="$1"
    URL_A="$2"
    URL="http://${XIQEMU_HOST}:20161/rest/openapi/$URL_A"
    CURL_OPTIONS="--silent"
    CURL_HEADER="Host: openapi.$Device"

    # Get the openAPI version and schema version
    #echo "Executing: curl ${CURL_OPTIONS} -H "${CURL_HEADER}" $URL"
    curl ${CURL_OPTIONS} -H "${CURL_HEADER}" $URL

}

#
# Execute a rest API on a local port 7777
#
# Args: device_ip URL
#
# URL = 
#
exec_rest_local_port() {
    
    IP="$1"
    URL_A="$2"
    URL="http://${IP}:7777/rest/openapi/$URL_A"
    #CURL_OPTIONS="--silent"
    #CURL_HEADER="Host: openapi.$Device"

    # Get the openAPI version and schema version
    #echo "Executing: curl ${CURL_OPTIONS} -H "${CURL_HEADER}" $URL"
    curl ${CURL_OPTIONS} $URL

}

#
# Check if the GNS3 server is alive
#
check_gns3_server () {
    EXIT_ON_ERROR=$1

    RESULT=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects" | grep "\[" | wc -l 2>/dev/null)
    if [ "$RESULT" = "0" ] ; then
        RESULT=$(ping $GNS3_SERVER_HOST -c 1 | grep " 1 received, " | wc -l)
        if [ "$RESULT" = "0" ] ; then
            echoErrGreen "ERROR: GNS3 SERVER: $GNS3_SERVER not reachable"
            if [ "$EXIT_ON_ERROR" = "exit_on_error" ] ; then
                exit 1
            fi
        else
            echoErrGreen "ERROR: GNS3 server $GNS3_SERVER_HOST is alive, however the GNS3 server application does not respond"
            if [ "$EXIT_ON_ERROR" = "exit_on_error" ] ; then
                exit 1
            fi
        fi
    fi

    # Success
    return 0
}

check_project_UUID () {
    # See if we already have one
    if ! [ "$UUID_PROJ" = "" ] ; then
        echo "$UUID_PROJ"
        return
    fi

    if [ "$GNS3_PROJECT_NAME" = "" ] ; then
        echoErrGreen "ERROR: No GNS3 project name" 
        echo ""
        return 
    fi

    check_gns3_server no_exit_on_error

    if [ "$?" = "0" ] ; then
        RESULT=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects")
        UUID_PROJ=$(jq --raw-output ".[] | select( .name == \"${GNS3_PROJECT_NAME}\" ).project_id" <<< "${RESULT}")
    fi

    echo "$UUID_PROJ"
}

#
# Function that returns the UUID for the project (UUID_PROJ)
#
get_project_UUID () {
    # See if we already have one
    if ! [ "$UUID_PROJ" = "" ] ; then
        echo "$UUID_PROJ"
        return
    fi

    if [ "$GNS3_PROJECT_NAME" = "" ] ; then
        echoErrGreen "ERROR: No GNS3 project name given to remove from GNS3 server" 
        echo ""
        return 
    fi

    check_gns3_server no_exit_on_error

    if [ "$?" = "0" ] ; then
        RESULT=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects")
        UUID_PROJ=$(jq --raw-output ".[] | select( .name == \"${GNS3_PROJECT_NAME}\" ).project_id" <<< "${RESULT}")
    fi

    if [ "$UUID_PROJ" = "" ] ; then
        echoErrGreen "ERROR: Project ${GNS3_PROJECT_NAME} on Server: ${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT} does not exist"
    fi
    echo "$UUID_PROJ"
}

#
# Return the UUID for the given switch
#
get_switch_UUID () {

    SW_NAME=$1    

    UUID_PROJ=$(get_project_UUID)

    RESULT=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes")
    UUID_NODE=$(jq --raw-output ".[] | select( .name == \"$SW_NAME\" ).node_id" <<< "${RESULT}")

    if [ "$UUID_NODE" = "" ] ; then
        echoErrGreen "ERROR: Could not find UUID node for switch: $SW_NAME"
    fi

    echo "$UUID_NODE"
    return
} 

#
# Function that removes a GNS3 project from the server
#
remove_gns3_project () {

    if [ "$GNS3_PROJECT_NAME" = "" ] ; then
        echo "ERROR: No GNS3 project name given to remove from GNS3 server"
        return 1
    fi

    check_gns3_server no_exit_on_error
    if [ "$?" = "0" ] ; then
        RESULT=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects")
        UUID_PROJ=$(jq --raw-output ".[] | select( .name == \"${GNS3_PROJECT_NAME}\" ).project_id" <<< "${RESULT}")
        if ! [ "${UUID_PROJ}" = "" ] ; then
           echo "Removing project: ${GNS3_PROJECT_NAME}"
           curl --fail --silent --show-error --location --request DELETE "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}" > /dev/null || true
           UUID_PROJ=""
           #echo "Removed project: ${GNS3_PROJECT_NAME}"
        fi
    fi
}

create_new_project () {

    scene_width=$1
    scene_height=$2
    drawing_grid_size=$3
    grid_size=$4
    show_grid=$5
    snap_to_grid=$6

    # Make sure an old project is removed first
    remove_gns3_project

    # Create the new project
    RESULT=$(curl --fail --silent --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects" --data "{\"name\": \"${GNS3_PROJECT_NAME}\"}")

    # Store the UUID for later use
    UUID_PROJ=$(jq --raw-output ".project_id" <<< "${RESULT}")

    # Set the projects params
    curl --fail --silent --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}" --data "{\
        \"scene_width\": $scene_width, \
        \"scene_height\": $scene_height, \
        \"drawing_grid_size\": $drawing_grid_size, \
        \"grid_size\": $grid_size, \
        \"show_grid\": $show_grid, \
        \"snap_to_grid\": $snap_to_grid \
        }" > /dev/null

    curl --fail --silent --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/open" --data "{}" > /dev/null
    echo "GNS3 server:${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT} -> New project: ${GNS3_PROJECT_NAME} UUID:${UUID_PROJ}"
}

#
# Create a LAN node that creates a connection to the LAN network
#
create_LAN_node () {

    CLOUD_NAME=$1
    XPOS=$2
    YPOS=$3
    LABEL_XPOS=$4
    LABEL_YPOS=$5

    CLOUD_TEMPLATE="39e257dc-8412-3174-b6b3-0ee3ed6a43e9"
    CLOUD_NAME="LAN"
    COMPUTE_ID="local"

    # Check if the template exists
    #R=`curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates" | grep "$CLOUD_TEMPLATE" | wc -l`
    #if [ "$R" = "0" ] ; then
    #    echo "  Cloud LAN template not installed, adding new Cloud LAN template"
    #    R=`curl --fail --silent --show-error --location -X POST http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates \
    #        -H "Content-Type: application/json" \
    #        -d '{ \
    #        "name": "Cloud LAN", \
    #        "template_type": "cloud", \
    #        "compute_id": "local", \
    #        "adapters": 1 \
    #        }'`
    #fi

    echo "Creating \"Cloud\" LAN connection: $CLOUD_NAME with adapter: $GNS3_LAN_ADAPTER port: $GNS3_LAN_PORT and template: $CLOUD_TEMPLATE"
    RESULT=$(curl --fail --silent --show-error --location --request POST \
        "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/templates/${CLOUD_TEMPLATE}" --data \
        "{\"name\": \"LAN\", \"compute_id\": \"${COMPUTE_ID}\", \"x\": $XPOS, \"y\": $YPOS}")

    UUID_UNET=$(jq --raw-output ".node_id" <<< "${RESULT}")
    echo "  Created LAN Cloud node: UUID:$UUID_UNET, setting name and symbol"
    curl --fail --silent --show-error --location --request PUT \
        "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_UNET}" --data "{
        \"name\": \"${CLOUD_NAME}\", \"symbol\": \":/symbols/affinity/square/gray/cloud.svg\",\
        \"label\": {\"rotation\": 0, \"style\": \"null\", \"text\": \"LAN\", \"x\": $LABEL_XPOS, \"y\": $LABEL_YPOS}}" > /dev/null
}

#
# Create a SubNetRouter node in the project
#
create_subNetRouter_node () {
    XPOS=$1
    YPOS=$2
    LABEL_XPOS=$3
    LABEL_YPOS=$4

    #
    # First need to see if the right template is present for the SubNetRouter
    #
    R=`curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates" | grep "SubNetRouter" | wc -l`
    if [ "$R" = "0" ] ; then

        # Template is not available, create it
        echo "  SubNetRouter template not installed, adding new SubNetRouter template"
        R=`curl --fail --silent --show-error --location -X POST http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates \
            -H "Content-Type: application/json" \
            -d '{ \
            "name": "SubNetRouter", \
            "template_type": "docker", \
            "compute_id": "local", \
            "image": "ubserver:latest", \
            "adapters": 2, \
            "console_type": "telnet" \
            }'`
    fi

    # Retrieve the templace ID
    snt_t_id=0
    snt_t_id=$(curl --fail --silent --show-error --location --request GET "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/templates" | jq -r '.[] | select(.name=="SubNetRouter") | .template_id')
    echo "  Using SubNetRouter template ID: $snt_t_id"

    # Determine if we have a route to the test network
    # Uses SUBNET_ROUTER_GATEWAY and SUBNET_ROUTER_NETWORK from gns3.cfg
    if [ -n "$SUBNET_ROUTER_GATEWAY" ] && [ -n "$SUBNET_ROUTER_NETWORK" ]; then
        R=`ip route | grep "$SUBNET_ROUTER_GATEWAY" | wc -l`
        if [ "$R" = "0" ] ; then
            # Need to install the route
            echo "Installing route to $SUBNET_ROUTER_NETWORK through gateway $SUBNET_ROUTER_GATEWAY"
            ip route add $SUBNET_ROUTER_NETWORK via $SUBNET_ROUTER_GATEWAY
        fi
    fi

    if [ "$snt_t_id" = "0" ] ; then
        echo "  *** ERROR *** : SubNetRouter template ID could not be found"
        exit 1
    fi

    # Create the ubserverR router
    template_ID="$snt_t_id" 
    RESULT=$(curl  --fail  --show-error --location --request POST "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/templates/$template_ID" \
        --data "{\"name\": \"Subnet Router\", \"compute_id\": \"${COMPUTE_ID}\", \"x\": $XPOS, \"y\": $YPOS}")
    UUID_SROUTER=$(jq --raw-output ".node_id" <<< "${RESULT}")
    curl --fail --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_SROUTER}" \
        --data "{\"name\": \"Subnet Router\"}" > /dev/null
    curl --fail --show-error --location --request PUT "http://${GNS3_SERVER_HOST}:${GNS3_SERVER_PORT}/v2/projects/${UUID_PROJ}/nodes/${UUID_SROUTER}" \
        --data "{\"symbol\": \":/symbols/classic/router.svg\",\
        \"label\": {\"rotation\": 0, \"style\": \"null\", \"text\": \"LAN\", \"x\": $LABEL_XPOS, \"y\": $LABEL_YPOS}}" > /dev/null

    # Link the eth0 of the Subnet Router to the UNET cloud adapter
    connect_nodes "${UUID_UNET}" "${GNS3_LAN_ADAPTER}" "${GNS3_LAN_PORT_NR}" "${GNS3_LAN_PORT}" "${UUID_SROUTER}" 0 0 "eth0"
    echo "  SubNetRouter UUID:$UUID_SROUTER"
}

