#!/bin/bash

# Set the python environment
source venv/bin/activate

# Set the directory paths
cpath=`pwd`
echo "cpath set to: -- ${cpath} --"
export ANSIBLE="${cpath%/tests/integration/harness}"
export ANSIBLE_CONFIG="${cpath}/cfg/ansible.cfg"

# Source the GNS3 configuration
source cfg/gns3.cfg

#-------------------------------------------------------------
# Sanity checks:
#-------------------------------------------------------------

# Make sure docker is installed
if ! command -v docker &> /dev/null
then
  echo "docker could not be found, please install it."
  exit 1
fi

# Make sure gns3server is installed
if ! command -v gns3server &> /dev/null
then
  echo "gns3server could not be found, please install it."
  exit 1
fi

# ------------------------------------------------------------------------------
# Start the servers ...
# ------------------------------------------------------------------------------
gns3server --host 0.0.0.0 --port 3080 --local -A 
