#!/bin/bash

# Set the python environment
source venv/bin/activate

# Set the directory paths
cpath=`pwd`
export ANSIBLE="${cpath%/tests/integration/harness}"
export ANSIBLE_CONFIG="${cpath}/cfg/ansible.cfg"

# Determine the hosts IP address
my_ip=$(ip addr show | grep 'inet ' | grep -v '127.0.0.1' | grep -v docker | grep -v virbr| awk '{print $2}' | cut -d'/' -f1 | head -n1)

# Update the GNS3_SERVER_HOST variable in the gns3.cfg file in case it has changed
sed -i -E "s/^(GNS3_SERVER_HOST=).*/\1\"${my_ip}\"/" "${cpath}/cfg/gns3.cfg"

# Determine if the host IP needs to be updated in the docker ubserver image
UBH=`cat $ANSIBLE/tests/integration/harness/docker/ubserver/dashboard-server-ip`
if [ "$my_ip" != "$UBH" ] ; then
  echo "Host IP has changed from $UBH to $my_ip, updating ubserver image"
  echo $my_ip > $ANSIBLE/tests/integration/harness/docker/ubserver/dashboard-server-ip
fi

# Source the GNS3 configuration
source cfg/gns3.cfg

# ------------------------------------------------------------------------------
# Start the server
# ------------------------------------------------------------------------------
echo "You can access the dashboard at http://$my_ip:4000"
python3 ./dashboard_server.py 1>&2 2>/tmp/dashboard.log 