#!/usr/bin/expect --

#
# Script to ssh to a DT and then interact with the user
#
# ARGS: <IP> <username> <passwd>
#

# Include helper functions

log_user 1
#exp_internal -f /tmp/exp_debug 0

# globals
set ret 0
set err ""
set output ""
set id 0
set spawn_id ""
set cli_ret ""
set prompt "FabricEngine"

# Retrieve the IP
set ip [lindex $argv 0]
set userid [lindex $argv 1]
set pw [lindex $argv 2]

# ssh to the machine
spawn ssh $userid@$ip

    # send the password
    catch {
        expect {

            timeout {
                puts "Error: Timeout waiting for password prompt while ssh to $ip\n"
                exit
            }

            "assword:" {
                send "$pw\n";
                interact
                catch { close }
                catch { wait -nowait }
                exit 0
            }
        }

        expect {
            timeout {
                close
                wait -nowait
                puts "Error: Timeout waiting for prompt $prompt while ssh to $ip\n"
                exit
            }

            "$prompt" {
                interact
                catch { close }
                catch { wait -nowait }
                exit
            }
        }
    } 

    catch { close }
    catch { wait -nowait }
    puts "Error opening SSH session to ip $ip"
    exit