#!/usr/bin/bash

cd /etc/network

if ! [ -f interfaces ] ; then
  echo "No interfaces file found" >> /etc/network/log.txt
fi

if ! [ -f /home/ubuntu/interfaces.new ] ; then
  echo "No interfaces.new file found" >> /etc/network/log.txt
fi

LIP=`ip addr show dev eth0 | grep "link/ether" | awk '{ print $2 }' | sed 's/:/ /g' | awk '{ print $6 }'`

echo "ip addr show dev eth0 :">>/etc/network.log
ip addr show dev eth0 >>/etc/network.log

echo "LIP=$LIP">>/etc/network.log

while [ 1 = 1 ] 
do
  d=`diff interfaces /home/ubuntu/interfaces.new | wc -l`
  if [ "$d" = "0" ] ; then
    echo "No diff anymore, bring up interfaces" >> /etc/network/log.txt
    ifup eth0
    ifup eth1
    echo "No diff, exit"
    exit 0
  else
    echo "Bringing down interfaces"
    ifdown eth0
    ifdown eth1

    echo "Copy interface.new"
    # Replace the mgmt ip
    cat /home/ubuntu/interfaces.new | sed "s/NEWIP/$LIP/" >interfaces

    echo "copied interfaces file" >> /etc/network/log.txt
    sleep 2
    ifup eth0
    ifup eth1
    ifconfig
    echo "exitting"
    exit 0
  fi
  sleep 2 
done
