#!/usr/bin/bash

# Setup the right interfaces -- They are overwritten by GNS3
/home/ubuntu/check_interfaces

# Start the sshd
/usr/sbin/sshd 

# Start the DHCP server on eth1
# touch /var/lib/dhcp/dhcpd.leases
# /usr/sbin/dhcpd -4 --no-pid eth1


# Setup NAT forwarding
#nft add table ip nat
#nft add chain ip nat POSTROUTING { type nat hook postrouting priority 100 \; }
#nft add rule ip nat POSTROUTING oif "eth0" masquerade

# Start the REST server on port 8000
cd /app

# Start the REST API server to manage the ports amd IPs
python3 -m uvicorn app:app --host 0.0.0.0 --port 8000 &

# Start the File server on port 5000, Storing files in ./files
# Authenticate with user=extreme, password=networks
python3 FileServer.py &

# Install a DNS server
printf "nameserver 1.1.1.1\nnameserver 8.8.8.8\n" > /etc/resolv.conf

# Extract the last digit of the IP on eth0
HD=`ip addr show dev eth0 | grep inet | grep 192.168.5 | awk '{ print $2 }' | sed 's/\./ /g' | sed 's/\// /g' | awk '{ print $4 }'`

HD="TPC-${HD}"
hostname ${HD}
echo "${HD}" > /etc/hostname
sed -i "s/^\(127\.0\.1\.1\s*\).*/\1${HD}/" /etc/hosts || true

# Start LLDP
/usr/sbin/lldpd

while [ 1 = 1 ] 
do
  bash
done

