---
- name: Configuration cleanup
  hosts: gns3_network
  gather_facts: false
  tasks:

    - name: 00.01 - I-SID cleanup
      ansible.builtin.command:
        cmd: >-
          python3 {{ playbook_dir }}/../tests/integration/harness/tools/clean_isid.py
          {{ inventory_hostname }}
      register: isid_cleanup_result
      failed_when: isid_cleanup_result.rc != 0

    - name: 00.02 - VLAN cleanup
      ansible.builtin.command:
        cmd: >-
          python3 {{ playbook_dir }}/../tests/integration/harness/tools/clean_vlan.py
          {{ inventory_hostname }}{% if inventory_hostname == 'fe_dt_2' %} -s4040{% endif %}
      register: vlan_cleanup_result
      failed_when: vlan_cleanup_result.rc != 0

    - name: 00.03 - Autosense cleanup
      ansible.builtin.command:
        cmd: >-
          python3 {{ playbook_dir }}/../tests/integration/harness/tools/clean_autosense.py
          {{ inventory_hostname }}{% if inventory_hostname == 'fe_dt_2' %} -s1:1{% endif %}
      register: autosense_cleanup_result
      failed_when: autosense_cleanup_result.rc != 0

    - name: 01.00 - Cleanup configuration
      extreme.fe.extreme_fe_command:
        commands:
          - enable
          - terminal more disable
          - configure terminal
          - interface gigabitEthernet 1/22
          - lacp key 1237
          - interface gigabitEthernet 1/20-1/23
          - no lacp enable
          - no lacp aggregation enable
          - interface gigabitEthernet 1/1,1/10
          - default poe poe-limit
          - default poe poe-priority
          - default poe fast-poe-enable
          - exit
          - no lacp enable
          - no mlt 10
          - no mlt 11
          - no mlt 15
          - no mlt 31
          - no mlt 32
          - no mlt 33
          - no mlt 34
          - no virtual-ist peer-ip
          - no i-sid name 100
          - no i-sid name 202
          - no i-sid name 203
          - no i-sid name 204
          - no i-sid name 220
          - no i-sid name 221
          - router isis enable
        continue_on_failure: true
