---
- name: Delete VLANs 2 through 14 and 20 on ExtremeNetworks Fabric Engine switches
  hosts: gns3_network
  gather_facts: false
  collections:
    - extreme.fe
  vars:
    vlan_list:
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "20"
  tasks:
    - name: Ensure VLAN is absent
      extreme.fe.extreme_fe_vlans:
        vlan_id: "{{ vlan_id | int }}"
        vr_name: GlobalRouter
        state: deleted
      loop: "{{ vlan_list }}"
      loop_control:
        loop_var: vlan_id
        label: "VLAN {{ vlan_id }}"
