---
- name: Remove IPv4 address 10.0.1.101/24 from VLAN 20
  hosts: fe_dt_1
  gather_facts: false
  tasks:
    - name: Delete IPv4 address from VLAN 20
      extreme.fe.extreme_fe_l3_interfaces:
        state: deleted
        config:
          - vlan_id: 20
            name: VLAN 20
            ipv4:
              - 10.0.1.101/24
