---
- name: Gather Fabric Engine neighbor facts
  hosts: gns3_network
  gather_facts: false
  tasks:
    - name: Collect neighbors subset
      extreme.fe.extreme_fe_facts:
        gather_subset:
          - neighbors
      register: fe_neighbors

    - name: Show neighbor facts
      debug:
        var: fe_neighbors.ansible_facts.extreme_fe_facts.neighbors
