---
- name: Gather Fabric Engine interface facts
  hosts: gns3_network
  gather_facts: false
  tasks:
    - name: Collect interfaces subset
      extreme.fe.extreme_fe_facts:
        gather_subset:
          - interfaces
      register: extreme_fe_interfaces

    - name: Show interface facts
      debug:
        var: extreme_fe_interfaces.ansible_facts.extreme_fe_facts.interfaces
