---
- name: Delete VLANs 2 through 500 on ExtremeNetworks Fabric Engine switches
  hosts: gns3_network
  gather_facts: false
  collections:
    - local.extreme_fe
  vars:
    vlan_list:
      - "2"
      - "30"

  tasks:
    - name: Gather VLAN snapshot
      extreme.fe.extreme_fe_vlans:
        state: gathered
        gather_filter: "{{ vlan_list | map('int') | list }}"
      register: vlan_snapshot
