---
- name: Configure VLAN 5 on ports 1:5 and 1:6
  hosts: gns3_network
  gather_facts: false
  vars:
    access_ports:
      - PORT:1:5
      - PORT:1:6
  tasks:
    - name: Ensure VLAN 5 exists
      extreme.fe.extreme_fe_vlans:
        vlan_id: 5
        vlan_name: Campus-5
        vr_name: GlobalRouter
        state: merged

    - name: Configure VLAN 5 access interface
      extreme.fe.extreme_fe_l2_interfaces:
        interface: "{{ interface }}"
        port_type: TRUNK
        tagged_vlans: [5]
        untagged_vlan: 0
        state: replaced
      loop: "{{ access_ports }}"
      loop_control:
        loop_var: interface
        label: "{{ interface }}"
