---
- name: Delete VLAN 500 on ExtremeNetworks Fabric Engine switches
  hosts: gns3_network
  gather_facts: false
  tasks:
    - name: Remove VLAN 500 if present
      extreme.fe.extreme_fe_vlans:
        vlan_id: 500
        vr_name: GlobalRouter
        state: deleted
