#!/usr/bin/bash

# Setup the right interfaces -- They are overwritten by GNS3
/home/ubuntu/check_interfaces

# Start the sshd
/usr/sbin/sshd 

# Start the DHCP server on eth1
touch /var/lib/dhcp/dhcpd.leases
/usr/sbin/dhcpd -4 --no-pid eth1

# Setup NAT forwarding
nft add table ip nat
nft add chain ip nat POSTROUTING { type nat hook postrouting priority 100 \; }
nft add rule ip nat POSTROUTING oif "eth0" masquerade

# Send my IP address to the dashboard, this is needed in case we are using a DHCP client to the LAN side
/home/ubuntu/send-ip-address &

bash
while [ 1 = 1 ] 
do
  sleep 100000
done

