#!/usr/bin/bash

cd /etc/network

if ! [ -f interfaces ] ; then
  echo "No interfaces file found" >> /etc/network/log.txt
fi

if ! [ -f /home/ubuntu/interfaces.new ] ; then
  echo "No interfaces.new file found" >> /etc/network/log.txt
fi

echo "check_interfaces: Bringing down interfaces"
ifdown eth0
ifdown eth1

while [ 1 = 1 ] 
do
  d=`diff interfaces /home/ubuntu/interfaces.new | wc -l`
  if [ "$d" = "0" ] ; then
    echo "No diff anymore, bring up interfaces" >> /etc/network/log.txt
    ifup eth0
    ifup eth1
    echo "check_interfaces: Bringing up interfaces, exit"
    ip addr
    exit 0
  else
    echo "Copy interface.new"
    cp /home/ubuntu/interfaces.new interfaces
    echo "copied interfaces file" >> /etc/network/log.txt
    echo "check_interfaces: Interfaces configured"
  fi
  sleep 5 
done
